### ISSUE TITLE
Sending Error in the Web GUI

### ISSUE THREAD

**Issue by huangwb8** [PrivateBin/docker-nginx-fpm-alpine#102]
I tried using Docker to install PrivateBin. Here is the docker compose yaml :

```yml
version: "3.7"

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    read_only: true
    volumes:
      - './privatebin-data:/srv/data'
      # - './conf.php:/srv/cfg/conf.php:ro'
    ports:
      - $Port:8080
    restart: always
    networks:
      - default

networks:
  default:
    name: privatebin
```
When I tested the pasting and sending of PrivateBin, the error appeared:
![image](https://user-images.githubusercontent.com/35643122/173964310-8f1ea056-a465-4a92-9331-6c93215981c2.png)

It means that the content could not be sent.

Any suggestions?
