### ISSUE TITLE
Error in sending files with PrivateBin-MYSQL

### ISSUE THREAD

**Issue by huangwb8** [PrivateBin/docker-nginx-fpm-alpine#103]
Hi, I try to use PrivateBin with MYSQL in Docker. Here is some settings of my files:

My `conf.php`:

```php
<?php
[main]
name = "BenszPrivateBin"
discussion = true
fileupload = ture
sizelimit = 104857600
languageselection = false
    
[model]
class = Database
[model_options]
dsn = "mysql:host=db;dbname=privatebin;charset=UTF8"
tbl = "privatebin_"
usr = "privatebin"
pwd = "abcde"
opt[12] = true

```

my `php.ini`:

```ini
[PHP]

; Enable the PHP scripting language engine under Apache.
; http://php.net/engine
engine = On

; This directive determines whether or not PHP will recognize code between
; <? and ?> tags as PHP source which should be processed as such. It is
; generally recommended that <?php and ?> should be used and that this feature
; should be disabled, as enabling it may result in issues when generating XML
; documents, however this remains supported for backward compatibility reasons.
; Note that this directive does not control the <?= shorthand tag, which can be
; used regardless of this directive.
; Default Value: On
; Development Value: Off
; Production Value: Off
; http://php.net/short-open-tag
short_open_tag = Off

; The number of significant digits displayed in floating point numbers.
; http://php.net/precision
precision = 14

; Output buffering is a mechanism for controlling how much output data
; (excluding headers and cookies) PHP should keep internally before pushing that
; data to the client. If your application's output exceeds this setting, PHP
; will send that data in chunks of roughly the size you specify.
; Turning on this setting and managing its maximum buffer size can yield some
; interesting side-effects depending on your application and web server.
; You may be able to send headers and cookies after you've already sent output
; through print or echo. You also may see performance benefits if your server is
; emitting less packets due to buffered output versus PHP streaming the output
; as it gets it. On production servers, 4096 bytes is a good setting for performance
; reasons.
; Note: Output buffering can also be controlled via Output Buffering Control
;   functions.
; Possible Values:
;   On = Enabled and buffer is unlimited. (Use with caution)
;   Off = Disabled
;   Integer = Enables the buffer and sets its maximum size in bytes.
; Note: This directive is hardcoded to Off for the CLI SAPI
; Default Value: Off
; Development Value: 4096
; Production Value: 4096
; http://php.net/output-buffering
output_buffering = 4096

; Maximum allowed size for uploaded files.
upload_max_filesize = 100M

; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; http://php.net/post-max-size
post_max_size = 100M

; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 3072M

; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 180
```
My docker-compose.yml:

```yaml

version: "3.7"

services:
  app:
    image: privatebin/nginx-fpm-alpine:latest
    restart: unless-stopped
    read_only: false
    volumes:
      - './privatebin-data:/srv/data'
      - './conf.php:/srv/cfg/conf.php:ro'
      - './php.ini:/etc/php7/php.ini:ro'
    ports:
      - 8080:8080
    networks: 
      - default
  
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: privatebin
      MYSQL_USER: privatebin
      MYSQL_PASSWORD: abcde
    volumes:
      - './db:/var/lib/mysql'
    networks:
      - default

networks:
  default:
    name: privatebin
```
When run `docker-compose up` and send a file in PrivateBin, Error exist:
![image](https://user-images.githubusercontent.com/35643122/174438184-bdb57358-490b-4dbe-8a51-541d2bec697b.png)
Here is the logs:
```
privatebin-app-1  | 2022/06/18 12:39:00 [error] 21#21: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS "comment_parent" ON "privatebin_comment" ("pasteid")' at line 1 in /srv/lib/Data/Database.php:842
privatebin-app-1  | Stack trace:
privatebin-app-1  | #0 /srv/lib/Data/Database.php(842): PDO->exec()
privatebin-app-1  | #1 /srv/lib/Data/Database.php(124): PrivateBin\Data\Database::_createCommentTable()
privatebin-app-1  | #2 [internal function]: PrivateBin\Data\Database::getInstance()
privatebin-app-1  | #3 /srv/lib/Model.php(86): forward_static_call()
privatebin-app-1  | #4 /srv/lib/Controller.php(199): PrivateBin\Model->getStore()
privatebin-app-1  | #5 /srv/lib/Controller.php(125): PrivateBin\Controller->_create()
privatebin-app-1  | #6 /var/www/index.php(18): PrivateBin\Controller->__construct()
privatebin-app-1  | #7 {main}
privatebin-app-1  |   thrown in /srv/lib/Data/Database.php on line 842" while reading response header from upstream...
```
Any suggestions?
