### ISSUE TITLE
Latest Update broke container for me

### ISSUE THREAD

**Issue by podkilla** [PrivateBin/docker-nginx-fpm-alpine#16]
Here is a line from the log.

```
privatebin    | 2020/05/04 18:04:21 [emerg] 270#270: socket() [::]:8080 failed (97: Address family not supported by protocol)
privatebin    | nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)
```

this is my docker-compose.yml file
```
---
version: "2"
services:
    privatebin:
        image: privatebin/nginx-fpm-alpine
        container_name: privatebin
        ports:
          - "127.0.0.1:8080:80"
        environment:
          - TZ=Europe/Amsterdam  
          - PHP_TZ=Europe/Amsterdam
        volumes:
          - /var/docker/conf/privatebin/conf.php:/src/cfg/conf.php:ro
          - /etc/localtime:/etc/localtime:ro  
        restart: unless-stopped
```

My guess is that it has something to do with the ipv6 stack, which i dont have on my docker host.
