### ISSUE TITLE
Environment variable to change the internal port number

### ISSUE THREAD

**Issue by adcin** [PrivateBin/docker-nginx-fpm-alpine#212]
# Issue

Docker Compose has a nice element called [network_mode](https://docs.docker.com/reference/compose-file/services/#network_mode). I use it for example to connect the apps/services to my [Tailscale network](https://tailscale.com/kb/1282/docker?q=docker). The issue is, that a lot of devs use the internal port 8080 in their containers, and you can not redirect it easily with the ports element (e.g. `ports: - 9999:8080`).
Here is an example compose file:
```
---
name: myservices
services:
  myservices-tailscale:
    image: tailscale/tailscale:latest
    hostname: myservices-tailscale
    environment:
      - TS_AUTHKEY=tskey-client-xxxxxxxxxxxxxxxxxxxxxx?ephemeral=true
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/volumes/myservices-tailscale/var..lib..tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    ports:
      - 9888:8080 # Access to privatebin
      - 9999:8181 # Access to homer
    restart: unless-stopped

  myservices-privatebin
    image: privatebin/nginx-fpm-alpine
    volumes:
      - ${PWD}/volumes/myservices-privatebin/srv..data:/srv/data
      - ${PWD}/volumes/myservices-privatebin/srv..cfg/conf.php:/srv/cfg/conf.php:ro
    restart: unless-stopped
    network_mode: service:myservices-tailscale

  myservices-homer:
    image: b4bz/homer
    container_name: myservices-homer
    volumes:
      - ${PWD}/volumes/myservices-homer/www..assets:/www/assets
    environment:
      - PORT=8181 # Luckily homer supports this option
    restart: unless-stopped
    network_mode: service:myservices-tailscale
```
So when a service is using the element `network_mode: service:myservices-tailscale`, then it can not use the element `ports:`.
A workaround is, to use the `ports:` element just in the network service container "myservices-tailscale". But in this case the internal container ports of all the other services must be unique. So `9888:8080 and 9999:8181` works fine, but `9888:8080 and 9999:8080` not.

Luckily the container b4bz/homer has a `PORT` environment variable, and I can change this containers default port from 8080 to 8181, so it does not collide with privatebin's port 8080. But a lot of services do not have this option, so they can not be added to this example Docker Compose yaml.

# Current status

I hope I see it correctly that the internal port number is currently hard coded to 8080 and there is no environment variable available to change this. Well, unless I create a custom image myself.

# Feature request

Add an optional PORTS variable, so the default port 8080 can be changed easily.
