### ISSUE TITLE
413 NGINX error on large uploads (more than 15Mb)

### ISSUE THREAD

**Issue by ciaens** [PrivateBin/docker-nginx-fpm-alpine#213]
Hello team,

I've been using PrivateBin for a while now, and I deeply thank the maintainers for their work.
I'm facing recently issues when uploading documents bigger than 15Mb. 
--> Expectation : NGINX client_max_body_size is the value specified in the configuration passed to the container.
I did not bisect the version in which it happens.

My setup : 
`Debian 12 Bookworm`, `Docker CE 5:28.1.1-1~debian.12~bookworm`

My docker compose : 
```
---
services:
  privatebin-protected:
    image: privatebin/nginx-fpm-alpine:latest
    restart: always
    ports:
      - "127.0.0.1:8282:8080"
    volumes:
      - privatebin_data:/srv/data
      - ./conf_protected.php:/srv/cfg/conf.php:ro
    environment:
      - TZ=Europe/Paris
      - PHP_TZ=Europe/Paris

volumes:
  privatebin_data:
    name: privatebin_data
```

I'm using Apache2 in front for SSL termination.
In my conf_protected.php : 
```
; size limit per paste or comment in bytes, defaults to 10 Mebibytes
sizelimit = 104857600
```
It should be set around 100Mb (I added an extra 0 at the end of the default value).

However, in /etc/nginx/nginx.conf, there is a hardcoded limit of 15Mb : 
```
    # Allow up to 15 MiB payload, privatebin defaults to 10 MiB.
    client_max_body_size 15M;
```

My current workaround is to change it in the container, but it doesn't survive a restart.
