### ISSUE TITLE
timeout while the service is up!

### ISSUE THREAD

**Issue by NoxInmortus** [PrivateBin/docker-nginx-fpm-alpine#27]
Hello,

I noticed that privatebin log is fulled by thoses :
```
s6-supervise php-fpm8: warning: can't happen: timeout while the service is up!
s6-supervise nginx: warning: can't happen: timeout while the service is up!
```

Currently using latest docker version with Swarm, this is privatebin configuration:

```yaml
  - name: privatebin
    image: privatebin/nginx-fpm-alpine
    restart_policy: any
    mode: replicated
    replicas: 1
    env:
     TZ: Europe/Paris
     PHP_TZ: Europe/Paris
    mounts:
      - source: privatebin
        target: /srv/data
        type: volume
    networks:
      - name: net-traefik
        aliases:
          - privatebin.{{ domain_name }}
    labels:
      traefik.enable: 'true'
      traefik.docker.network: net-traefik
      traefik.http.routers.privatebin-http.entrypoints: http
      traefik.http.routers.privatebin-http.middlewares: https-redirect
      traefik.http.routers.privatebin-http.rule: Host(`privatebin.{{ domain_name }}`)
      traefik.http.routers.privatebin-https.entrypoints: https
      traefik.http.routers.privatebin-https.rule: Host(`privatebin.{{ domain_name }}`)
      traefik.http.routers.privatebin-https.tls: 'true'
      traefik.http.routers.privatebin-https.tls.options: 'default'
      traefik.http.routers.privatebin-https.middlewares: secure-headers,gzip
      traefik.http.routers.privatebin-https.service: 'privatebin-https'
      traefik.http.services.privatebin-https.loadbalancer.server.port: '8080'
```

Any clue about what is going on ?
