### ISSUE TITLE
error on raspberry pi 3b+

### ISSUE THREAD

**Issue by rev1e** [PrivateBin/docker-nginx-fpm-alpine#49]
Image doesn't work on raspberry pi 3b+. I tested latest and edge tags.
logs:
```
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise php-fpm8: fatal: unable to iopause: Operation not permitted
s6-svscan panicked! Dropping to a root shell.

s6-supervise nginx: fatal: unable to iopause: Operation not permitted
/bin/sh: can't access tty; job control turned off
/run/s6/services $
```

**Comment by elrido** [comment]
I've retested the 1.3.5 release and edge images on my k3s Pi3B cluster and it does work fine there. It must be a permission issue with the setup of your container runtime. For your reference, the log output on my containers looked like this:

```
[27-Jun-2021 06:23:57] NOTICE: fpm is running, pid 39
[27-Jun-2021 06:23:57] NOTICE: ready to handle connections
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

The YAML file applied with kubectl was this (note the lack of persistence - config for testing, not production):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin
  labels:
    app: privatebin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
#      initContainers:
#      - name: privatebin-volume-permissions
#        image: privatebin/chown
#        args: ['65534:82', '/mnt']
#        securityContext:
#          runAsUser: 0
#          readOnlyRootFilesystem: True
#        volumeMounts:
#        - mountPath: /mnt
#          name: privatebin-data
#          readOnly: False
      containers:
      - name: privatebin
        image: privatebin/nginx-fpm-alpine:1.3.5
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Europe/Zurich
        - name: PHP_TZ
          value: Europe/Zurich
        securityContext:
          runAsUser: 65534
          runAsGroup: 82
          readOnlyRootFilesystem: True
#        volumeMounts:
#        - mountPath: /srv/data
#          name: privatebin-data
#          readOnly: False
---
apiVersion: v1
kind: Service
metadata:
  name: privatebin
  labels:
    app: privatebin
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: ClientIP
  ports:
  - name: http
    protocol: TCP
    port: 30088
    targetPort: 8080
  selector:
    app: privatebin
```

The kernel and k8s server versions were these:
```
5.4.34-0-rpi2
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-k3s.1", GitCommit:"3d7d34a23ec464c08b81486aeca0b7d1bb6e044c", GitTreeState:"clean", BuildDate:"2020-04-19T05:33:19Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/arm"}
```

If you could share some more information on how your running the container (command or YAML to start the container) and the runtime you used (docker, podman, k8s, ...) and if the runtime has some non-standard configurations (i.e. usernamespace remapping, cgroups version set in kernel) we might work out what is different on your setup - there may even be a way to work around the issue without changing the configuration.

**Comment by rev1e** [comment]
I've tried starting container using this docker-compose configuration:
```
privatebin:
  image:  privatebin/nginx-fpm-alpine:latest
  restart: always
  volumes:
     - ./privatebin/:/srv/data
```
but also with
```
docker run --rm privatebin/nginx-fpm-alpine:latest
```
and results were the same. I run containers using Raspberry Pi OS with account which is in docker group. The kernel and docker versions are:
```
5.10.17-v7+
Docker version 20.10.7, build f0df350
```
I also run pihole and vaultwarden containers on this raspberry pi without issues.

PS I will not be able to reply for next week
