### ISSUE TITLE
How to run this on docker-compose traefik?

### ISSUE THREAD

**Issue by thepenguinthatwants** [PrivateBin/docker-nginx-fpm-alpine#5]
Hi!

I am trying to get this work on my server (which is using traefik) but first trying on localhost first at my laptop.

So I made this.

```
version: "3"
services:

  app:
    image: privatebin/nginx-fpm-alpine
    networks:
      - srv
    volumes:
      - '$PWD/paste:/srv/data'
    labels:
        - traefik.frontend.rule=Host:pbb.localhost
        - traefik.docker.network=srv
        - traefik.port=8080


networks:
  srv:
    external: true

```

But for some reasons I just get Bad Gateway

**Comment by elrido** [comment]
From the README.md:

> The Nginx webserver inside the container listens on port 80

In the example given we map this to 8080 under the assumption that you probably don't want to block your hosts port 80. I assume you have to tell traefik to use port 80 for connect to?

```
        - traefik.port=80
```

**Comment by thepenguinthatwants** [comment]
Sure u r awesome. Me not that much :D .. damn thanks

**Comment by thepenguinthatwants** [comment]
Could not create paste: server error or not responding

So I guess the another problem is with the persistence?

**Comment by thepenguinthatwants** [comment]
thrown in /srv/lib/Persistence/AbstractPersistence.php on line 99" while reading response header from upstream, client: 192.168.16.2, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "privatebin.localhost"

**Comment by elrido** [comment]
That is an issue with the permissions of the volume: Can you make sure that it is writeable to the environment in the container?

Likely cause is the ownership - the folder used as a volume needs to be owned by the UID that `nobody` (which the php-fpm daemon runs as) maps to, in your environment (that is UID 65534 on a standard docker environment, but it will be offset if you run this under user namespace isolation).

**Comment by thepenguinthatwants** [comment]
I thought adding enviroment variable PUID and PGID would correct them but seems like this is not enough.

```
version: "3"
services:

  app:
    image: privatebin/nginx-fpm-alpine
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - srv
    volumes:
      - '$PWD/paste:/srv/data'
    labels:
        - traefik.frontend.rule=Host:pbb.localhost
        - traefik.docker.network=srv
        - traefik.port=80


networks:
  srv:
    external: true
```
