### ISSUE TITLE
privatebin run issue on synology docker

### ISSUE THREAD

**Issue by yche2990** [PrivateBin/docker-nginx-fpm-alpine#59]
I just installed from scratch.

Unfortunately, I have the following error message:

s6-rc: fatal: unable to take locks: Permission denied

Any assistance is appreciated.

**Comment by lukasleitsch** [comment]
Having the same issue but on an ubuntu host. After starting a fresh container with an empty volume the error `s6-rc: fatal: unable to take locks: Permission denied` occurs.

- Ubuntu 20.04.2
- Docker version 20.10.8
- docker-compose version 1.29.2

I'm using the following `docker-compose.yml`:

```yaml
version: '3.7'

services:
  web:
    image: privatebin/nginx-fpm-alpine
    volumes:
      - privatebin-data:/srv/data
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: $HOST
      LETSENCRYPT_HOST: $HOST
    networks:
      - proxy
      - default

volumes:
  privatebin-data:

networks:
  proxy:
    external:
      name: nginx-proxy
```
