### ISSUE TITLE
Run on Kubernetes has permission problem

### ISSUE THREAD

**Issue by oliver-kriska** [PrivateBin/docker-nginx-fpm-alpine#8]
Hello,

We ran version < 1.3 on Kubernetes without issue. Folder `/srv/data` is mounted disk and shared between pods. After upgrade we had this error. Looks like it creates this error randomly. First, I thought it's problem with multiple pods, but now it creates this error even when only one pod is running. But after couple of tries it started working again. Maybe every 3-4th try end with this error. 
Error:
```
*5 FastCGI sent in stderr: "PHP message: PHP Warning:  mkdir(): Permission denied in /srv/lib/Data/Filesystem.php on line 64" while reading response header from upstream, client: 172.16.110.114, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host:
```

Part of our k8s deployment setup:
```yaml
securityContext:
  fsGroup: 82
initContainers:
- name: volume-mount-hack
  image: busybox
  command: ["sh", "-c", "chmod g+rwx /srv/data && chown 65534:82 /srv/data "]
  volumeMounts:
  - mountPath: /srv/data
    name: private-bin
containers:
- name: private-bin
  image: 'payout1/private_bin:1.3.1'
  imagePullPolicy: Always
  securityContext:
    runAsUser: 65534
    runAsGroup: 82
  volumeMounts:
  - name: config
    mountPath: /srv/cfg/
  - mountPath: /srv/data
    name: private-bin
```
But permissions are like this: 
```bash
/var/www $ ls -la /srv/
total 4
drwxr-xr-x    1 root     root            17 Oct  2 06:30 .
drwxr-xr-x    1 root     root             6 Oct  2 09:01 ..
drwxrwsrwx    3 root     www-data        75 Oct  2 09:01 cfg
drwxrwx---   86 nobody   www-data      4096 Oct  2 08:53 data
drwxrwxr-x    5 nobody   www-data       260 Oct  2 06:30 lib
drwxrwxr-x    1 nobody   www-data        24 Oct  2 06:30 tpl
drwxrwxr-x    5 nobody   www-data        90 Oct  2 06:30 vendor
/var/www $ ls -la /srv/data/
total 24
drwxrwx---   86 nobody   www-data      4096 Oct  2 08:53 .
drwxr-xr-x    1 root     root            17 Oct  2 06:30 ..
-rw-r--r--    1 nobody   nobody          19 Oct  1 15:07 .htaccess
-rw-r-----    1 nobody   www-data        45 Oct  2 08:53 purge_limiter.php
-rw-r-----    1 nobody   www-data       522 Oct  2 08:08 salt.php
-rw-r-----    1 nobody   www-data       130 Oct  2 08:53 traffic_limiter.php
```

**Comment by elrido** [comment]
I have to say that you seem to do everything the right way, the permissions you list seem to match those of the user / group of the securityContext. I assume that both containers run on the same worker node and therefore mount the same local directory?

**Comment by oliver-kriska** [comment]
>  I assume that both containers run on the same worker node
No, they don't run on same node, on different node. I updated my question a few minutes after I created. It looks like I have same issue with one container.
> therefore mount the same local directory?
I created PersistentVolumeClaim (NFS) for this deployment and all containers use exact same volume mounted at same place.

**Comment by elrido** [comment]
I have gotten the opportunity to work with a Kubernetes and NFS based persistent volume and out of curiosity tried to replicate your deployment provided above. I think the problem is that there is no /srv/data folder in the busybox image so the mount isn't accessible. Using a different path in the init container that exists, I got it working. Here is the updated deployment part:

```yaml
initContainers:
- name: volume-mount-hack
  image: busybox
  command: ["chown", "65534:82", "/mnt"]
  securityContext:
    runAsUser: 0
    readOnlyRootFilesystem: True
  volumeMounts:
  - mountPath: /mnt
    name: private-bin
    readOnly: False
containers:
- name: private-bin
  image: 'payout1/private_bin:1.3.1'
  imagePullPolicy: Always
  ports:
  - containerPort: 8080
  securityContext:
    runAsUser: 65534
    runAsGroup: 82
    readOnlyRootFilesystem: True
  volumeMounts:
  - name: config
    mountPath: /srv/cfg/
    readOnly: True
  - mountPath: /srv/data
    name: private-bin
    readOnly: False
```
